var products = [
    { name: "High-Performance Car Battery", description: "Reliable battery with long lifespan for various car models", price: 250000, stock: 30, categories: ["Automotive"], slug: "high-performance-car-battery" },
    { name: "Canvas Painting Set", description: "Complete set with canvases, paints, and brushes for artists", price: 350000, stock: 25, categories: ["Arts and Crafts", "Home & Garden"], slug: "canvas-painting-set" },
    { name: "Bestseller Novel Collection", description: "A set of the top 5 bestselling novels", price: 500000, stock: 40, categories: ["Books"], slug: "bestseller-novel-collection" },
    { name: "Trendy Summer Dress", description: "Light and stylish dress perfect for summer", price: 400000, stock: 50, categories: ["Clothing"], slug: "trendy-summer-dress" },
    { name: "Noise-Cancelling Headphones", description: "Premium headphones with active noise cancellation", price: 1200000, stock: 20, categories: ["Electronics"], slug: "noise-cancelling-headphones" },
    { name: "Organic Green Tea", description: "High-quality organic green tea leaves", price: 150000, stock: 60, categories: ["Food & Beverages", "Health & Beauty"], slug: "organic-green-tea" },
    { name: "Skincare Essential Kit", description: "A set of skincare products for a complete routine", price: 800000, stock: 45, categories: ["Health & Beauty"], slug: "skincare-essential-kit" },
    { name: "Ergonomic Office Chair", description: "Comfortable chair with adjustable features for long hours of work", price: 1500000, stock: 35, categories: ["Office", "Health & Beauty"], slug: "ergonomic-office-chair" },
    { name: "Adjustable Garden Tool Set", description: "Complete set of garden tools with adjustable handles", price: 650000, stock: 30, categories: ["Home & Garden", "Sports & Outdoor Activities"], slug: "adjustable-garden-tool-set" },
    { name: "Portable Camping Stove", description: "Compact stove ideal for outdoor cooking and camping", price: 400000, stock: 50, categories: ["Food & Beverages", "Sports & Outdoor Activities"], slug: "portable-camping-stove" },
    { name: "All-Season Car Tires", description: "Durable tires suitable for all weather conditions", price: 2000000, stock: 15, categories: ["Automotive"], slug: "all-season-car-tires" },
    { name: "Handcrafted Pottery Set", description: "Unique pottery set handcrafted by skilled artisans", price: 900000, stock: 18, categories: ["Arts and Crafts"], slug: "handcrafted-pottery-set" },
    { name: "Classic Detective Novels", description: "A collection of timeless detective novels", price: 450000, stock: 35, categories: ["Books", "Arts and Crafts"], slug: "classic-detective-novels" },
    { name: "Luxury Wool Sweater", description: "Warm and cozy sweater made from high-quality wool", price: 1000000, stock: 20, categories: ["Clothing"], slug: "luxury-wool-sweater" },
    { name: "Smart Home Security Camera", description: "High-definition camera with motion detection and smartphone connectivity", price: 1800000, stock: 28, categories: ["Electronics", "Home & Garden"], slug: "smart-home-security-camera" },
    { name: "Gourmet Coffee Beans", description: "Premium roasted coffee beans for the perfect brew", price: 200000, stock: 55, categories: ["Food & Beverages"], slug: "gourmet-coffee-beans" },
    { name: "Hydrating Facial Mist", description: "Refreshing mist that hydrates and revitalizes the skin", price: 250000, stock: 60, categories: ["Health & Beauty"], slug: "hydrating-facial-mist" },
    { name: "Executive Desk Organizer", description: "Elegant organizer for keeping office supplies neatly arranged", price: 350000, stock: 40, categories: ["Office"], slug: "executive-desk-organizer" },
    { name: "Indoor Herb Garden Kit", description: "Kit for growing herbs indoors with all necessary supplies", price: 550000, stock: 35, categories: ["Home & Garden"], slug: "indoor-herb-garden-kit" },
    { name: "Multi-Functional Hiking Backpack", description: "Durable backpack with multiple compartments for hiking and outdoor adventures", price: 750000, stock: 30, categories: ["Sports & Outdoor Activities"], slug: "multi-functional-hiking-backpack" },
    { name: "Car Detailing Kit", description: "Complete kit for washing and detailing your car", price: 400000, stock: 25, categories: ["Automotive"], slug: "car-detailing-kit" },
    { name: "Scrapbooking Starter Kit", description: "All-in-one kit for scrapbooking enthusiasts", price: 450000, stock: 30, categories: ["Arts and Crafts"], slug: "scrapbooking-starter-kit" },
    { name: "Science Fiction Trilogy", description: "A trilogy of best-selling science fiction novels", price: 700000, stock: 25, categories: ["Books"], slug: "science-fiction-trilogy" },
    { name: "Lightweight Sport Jacket", description: "Breathable and lightweight jacket for sports and outdoor activities", price: 500000, stock: 35, categories: ["Clothing", "Sports & Outdoor Activities"], slug: "lightweight-sport-jacket" },
    { name: "Bluetooth Smartwatch", description: "Stylish smartwatch with Bluetooth connectivity and fitness tracking", price: 1500000, stock: 22, categories: ["Electronics", "Health & Beauty"], slug: "bluetooth-smartwatch" },
    { name: "Artisan Olive Oil", description: "Premium quality olive oil from artisanal producers", price: 250000, stock: 60, categories: ["Food & Beverages"], slug: "artisan-olive-oil" },
    { name: "Deep Cleansing Facial Mask", description: "Facial mask that deeply cleanses and refreshes the skin", price: 300000, stock: 50, categories: ["Health & Beauty"], slug: "deep-cleansing-facial-mask" },
    { name: "Modern Desk Lamp", description: "Sleek and adjustable desk lamp for better workspace lighting", price: 350000, stock: 45, categories: ["Office", "Home & Garden"], slug: "modern-desk-lamp" },
    { name: "Garden Furniture Set", description: "Stylish outdoor furniture set perfect for relaxing in the garden", price: 2500000, stock: 10, categories: ["Home & Garden"], slug: "garden-furniture-set" },
    { name: "Car Vacuum Cleaner", description: "Portable vacuum cleaner designed for car interiors", price: 300000, stock: 50, categories: ["Automotive"], slug: "car-vacuum-cleaner" },
    { name: "Scrapbooking Supplies Bundle", description: "Bundle of essential scrapbooking supplies including paper, stickers, and embellishments", price: 600000, stock: 20, categories: ["Arts and Crafts"], slug: "scrapbooking-supplies-bundle" },
    { name: "Classic Novel Set", description: "Collection of timeless classic novels", price: 550000, stock: 25, categories: ["Books"], slug: "classic-novel-set" },
    { name: "Casual Knit Sweater", description: "Comfortable and stylish sweater made from soft knit fabric", price: 750000, stock: 30, categories: ["Clothing"], slug: "casual-knit-sweater" },
    { name: "Digital Camera", description: "High-resolution digital camera with various shooting modes", price: 2200000, stock: 12, categories: ["Electronics"], slug: "digital-camera" },
    { name: "Organic Herbal Tea Collection", description: "Assortment of herbal teas made from organic ingredients", price: 300000, stock: 40, categories: ["Food & Beverages"], slug: "organic-herbal-tea-collection" },
    { name: "Adjustable Desk Chair", description: "Ergonomic chair with adjustable height and lumbar support", price: 1200000, stock: 25, categories: ["Office"], slug: "adjustable-desk-chair" },
    { name: "Garden Tool Organizer", description: "Storage solution for organizing garden tools", price: 450000, stock: 30, categories: ["Home & Garden"], slug: "garden-tool-organizer" },
    { name: "Travel Coffee Maker", description: "Compact coffee maker designed for travel and outdoor use", price: 350000, stock: 35, categories: ["Food & Beverages", "Sports & Outdoor Activities"], slug: "travel-coffee-maker" },
    { name: "Multifunctional Printer", description: "All-in-one printer with scanning, copying, and printing functions", price: 1000000, stock: 18, categories: ["Electronics", "Office"], slug: "multifunctional-printer" },
    { name: "Stylish Sunglasses", description: "Trendy sunglasses with UV protection", price: 500000, stock: 40, categories: ["Clothing", "Sports & Outdoor Activities"], slug: "stylish-sunglasses" },
    { name: "Gourmet Chocolate Box", description: "Selection of artisanal chocolates in an elegant box", price: 300000, stock: 45, categories: ["Food & Beverages"], slug: "gourmet-chocolate-box" },
    { name: "Modern Wall Art", description: "Contemporary wall art that adds a stylish touch to any room", price: 1000000, stock: 20, categories: ["Arts and Crafts", "Home & Garden"], slug: "modern-wall-art" },
    { name: "High-Quality Backpack", description: "Durable and stylish backpack suitable for everyday use", price: 650000, stock: 30, categories: ["Clothing", "Sports & Outdoor Activities"], slug: "high-quality-backpack" },
    { name: "Portable Water Filter", description: "Compact filter ideal for outdoor adventures and emergencies", price: 400000, stock: 40, categories: ["Sports & Outdoor Activities"], slug: "portable-water-filter" },
    { name: "Elegant Table Lamp", description: "Stylish table lamp perfect for home decor and lighting", price: 500000, stock: 35, categories: ["Home & Garden"], slug: "elegant-table-lamp" },
    { name: "Compact Sewing Machine", description: "Portable sewing machine for home and travel use", price: 1200000, stock: 15, categories: ["Arts and Crafts", "Electronics"], slug: "compact-sewing-machine" },
    { name: "Multi-Function Kitchen Gadget", description: "Versatile kitchen tool for chopping, blending, and more", price: 600000, stock: 30, categories: ["Electronics", "Food & Beverages"], slug: "multi-function-kitchen-gadget" },
    { name: "Lightweight Tent", description: "Easy-to-carry tent for camping and outdoor events", price: 700000, stock: 22, categories: ["Sports & Outdoor Activities"], slug: "lightweight-tent" },
    { name: "Fitness Tracker", description: "Wearable device that tracks physical activity and health metrics", price: 800000, stock: 25, categories: ["Health & Beauty", "Electronics"], slug: "fitness-tracker" },
    { name: "Elegant Office Desk", description: "Modern desk with a sleek design and ample workspace", price: 1800000, stock: 12, categories: ["Office", "Home & Garden"], slug: "elegant-office-desk" }
];

module.exports = { products };
